export const ICONS = {
    'flagw': '../images/flagw.png',
    'house': '../images/house.png',
    'peace': '../images/peace.png',
    'sfb': '../images/sfb.png',
    'theater': '../images/theater.png',
    'info': '../images/info.png',
    'shakehand': '../images/shakehand.png',
    'camp': '../images/camp.png',
    'strike': '../images/strike.png',
    'meet': '../images/meet.png',
    'sfbmeet': '../images/sfbmeet.png',
    'grave': '../images/grave.png',
    'lecture': '../images/lecture.png',
    'construct': '../images/construct.png',
    'metal': '../images/metal.png',
    'seed': '../images/seed.png',
    'farm2': '../images/farm2.png',
    'farm1': '../images/farm1.png',
    'prison': '../images/prison.png',
    'circus': '../images/circus.png',
    'bakuninh': '../images/bakuninh.png',
    'home': '../images/home.png',
    'sfbhome': '../images/sfbhome.png',
    'music': '../images/music.png',
    'medicine': '../images/medicine.png'
};